"""Siswa, SiswaOauth: Init OAuth

Revision ID: 0d93802e51aa
Revises: 9476380de8a6
Create Date: 2024-03-23 06:37:28.585158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d93802e51aa'
down_revision = '9476380de8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_dance_siswaoauth',
    sa.Column('provider_siswa_id', sa.String(length=256), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_siswa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_siswaoauth')
    # ### end Alembic commands ###
