"""Kelas: Remove uid

Revision ID: 4813d484f303
Revises: dc3f866e8343
Create Date: 2024-03-05 23:08:53.830569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4813d484f303'
down_revision = 'dc3f866e8343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
