"""Siswa: Init

Revision ID: 6d4b454fe279
Revises: 
Create Date: 2024-02-23 14:07:38.405573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4b454fe279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=False),
    sa.Column('jenjang', sa.Integer(), nullable=True),
    sa.Column('kelas', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    # ### end Alembic commands ###
