"""Guru, Jadwal: Init

Revision ID: 74601b08809c
Revises: 0d93802e51aa
Create Date: 2024-03-23 23:26:55.625569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74601b08809c'
down_revision = '0d93802e51aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('mapel', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('jadwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jam', sa.Integer(), nullable=True),
    sa.Column('hari', sa.Integer(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('guru_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['guru.index'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jadwal')
    op.drop_table('guru')
    # ### end Alembic commands ###
