"""Siswa: Init

Revision ID: 7e174ee7c5d7
Revises: 
Create Date: 2024-02-20 18:06:05.256880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e174ee7c5d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=1000), nullable=False),
    sa.Column('jenjang', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    # ### end Alembic commands ###
