"""Siswa: Add kelas relationship

Revision ID: 9476380de8a6
Revises: 4813d484f303
Create Date: 2024-03-06 06:47:11.372217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9476380de8a6'
down_revision = '4813d484f303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kelas_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'kelas', ['kelas_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kelas_id')

    # ### end Alembic commands ###
