"""Siswa: Add role

Revision ID: c0afb98ff5c7
Revises: 6d4b454fe279
Create Date: 2024-02-23 14:33:22.086925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0afb98ff5c7'
down_revision = '6d4b454fe279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
