"""Siswa: uid: Change to string

Revision ID: dc3f866e8343
Revises: dd649c46bb91
Create Date: 2024-03-05 23:06:02.397347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc3f866e8343'
down_revision = 'dd649c46bb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
