"""Jenjang, Kelas: Init

Revision ID: dd649c46bb91
Revises: 3d7dc9f3bb86
Create Date: 2024-03-05 21:34:59.150906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd649c46bb91'
down_revision = '3d7dc9f3bb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenjang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenjang', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jenjang')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=100), nullable=False),
    sa.Column('jenjang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jenjang_id'], ['jenjang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kelas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelas')
    op.drop_table('jenjang')
    # ### end Alembic commands ###
